// <auto-generated />
using System;
using Lab12_New.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab12_New.Migrations
{
    [DbContext(typeof(Lab12Context))]
    [Migration("20220920135402_lab11")]
    partial class lab11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab12_New.DomainClass.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.HoaDonSanPham", b =>
                {
                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSanPham", "IdHoaDon");

                    b.HasIndex("IdHoaDon");

                    b.ToTable("SANPHAMHOADON");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.KhoHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KHOHANG");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.KhoHangSanPham", b =>
                {
                    b.Property<Guid>("IdKhoHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdKhoHang", "IdSanPham");

                    b.HasIndex("IdSanPham");

                    b.ToTable("KHOHANGSANPHAM");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SANPHAM");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.HoaDon", b =>
                {
                    b.HasOne("Lab12_New.DomainClass.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.HoaDonSanPham", b =>
                {
                    b.HasOne("Lab12_New.DomainClass.HoaDon", "HoaDon")
                        .WithMany("HoaDonSanPhams")
                        .HasForeignKey("IdHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab12_New.DomainClass.SanPham", "SanPham")
                        .WithMany("HoaDonSanPhams")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.KhoHangSanPham", b =>
                {
                    b.HasOne("Lab12_New.DomainClass.KhoHang", "KhoHang")
                        .WithMany("KhoHangSanPhams")
                        .HasForeignKey("IdKhoHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab12_New.DomainClass.SanPham", "SanPham")
                        .WithMany("KhoHangSanPhams")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.HoaDon", b =>
                {
                    b.Navigation("HoaDonSanPhams");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.KhoHang", b =>
                {
                    b.Navigation("KhoHangSanPhams");
                });

            modelBuilder.Entity("Lab12_New.DomainClass.SanPham", b =>
                {
                    b.Navigation("HoaDonSanPhams");

                    b.Navigation("KhoHangSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
